#!/usr/bin/env node
/**
 * migrate-make.js — create a new numbered migration file.
 *
 * Usage:
 *   npm run migrate:make -- <description>
 *
 * Example:
 *   npm run migrate:make -- add_webhook_deliveries_table
 *
 * The script finds the highest existing migration number, increments it by 1,
 * and writes an empty SQL stub:
 *
 *   backend/src/db/migrations/006_add_webhook_deliveries_table.sql
 *
 * Rules enforced here intentionally mirror those in timescale.ts:
 *   - Files are sorted lexicographically, so zero-padded three-digit prefixes
 *     are required for correct ordering up to migration 999.
 *   - Each file's checksum is frozen on first run; never edit an applied file.
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
const fs = require('fs');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const path = require('path');

const MIGRATIONS_DIR = path.join(__dirname, '..', 'src', 'db', 'migrations');

function main() {
  const args = process.argv.slice(2);
  const raw = args.join('_').trim();

  if (!raw) {
    console.error('Usage: npm run migrate:make -- <description>');
    console.error('Example: npm run migrate:make -- add_webhook_deliveries_table');
    process.exit(1);
  }

  // Sanitise: lowercase, replace spaces/hyphens with underscores, strip non-word chars
  const description = raw
    .toLowerCase()
    .replace(/[\s-]+/g, '_')
    .replace(/[^\w]/g, '');

  if (!description) {
    console.error('Error: description must contain at least one alphanumeric character.');
    process.exit(1);
  }

  // Find the highest existing sequence number
  const existing = fs
    .readdirSync(MIGRATIONS_DIR)
    .filter((f) => /^\d{3}_.*\.sql$/.test(f))
    .map((f) => parseInt(f.slice(0, 3), 10));

  const next = existing.length > 0 ? Math.max(...existing) + 1 : 1;
  const prefix = String(next).padStart(3, '0');
  const filename = `${prefix}_${description}.sql`;
  const fullPath = path.join(MIGRATIONS_DIR, filename);

  if (fs.existsSync(fullPath)) {
    console.error(`Error: migration file already exists: ${filename}`);
    process.exit(1);
  }

  const timestamp = new Date().toISOString();
  const template = `-- Migration ${prefix}: ${description}
-- Created: ${timestamp}
--
-- IMPORTANT: Once this migration has been applied to any environment its
-- checksum is frozen. Do NOT edit this file; create a new migration instead.
--
-- Write your SQL below this line.
`;

  fs.writeFileSync(fullPath, template, 'utf8');
  console.log(`Created migration: src/db/migrations/${filename}`);
}

main();
